server:
  port: 8001

spring:
  application:
    name: base-zuul
  zipkin:
    base-url: http://localhost:9003
  boot:
    admin:
      client:
        url: http://localhost:9002

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:9000/eureka/

zuul:
  routes:
    # 路由名称，随意
    test-provider:
      # 路由地址
      path: /api/provider/**
      # 该路由地址对应的服务名称
      serviceId: test-service-provider
    test-consumer:
      path: /api/consumer/**
      serviceId:  test-service-consumer
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
