server:
  port: 8070

spring:
  application:
    name: le-service-auth
  zipkin:
    base-url: http://localhost:9003
  boot:
    admin:
      client:
        url: http://localhost:9002
  redis:
    host: 149.248.8.106
    port: 6379
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/loveeat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:9000/eureka/
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: LeWebApp
  clientSecret: LeWebApp
  cookieDomain: loveeat.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/le.keystore
    secret: keystore
    alias: loveeat
    password: loveeatkeystore

