server:
  port: 8002

spring:
  application:
    name: test-service-consumer
  zipkin:
    base-url: http://localhost:9003
  boot:
    admin:
      client:
        url: http://localhost:9002

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:9000/eureka/
feign:
  hystrix:
    # 开启Feign的Hystrix熔断器支持
    enabled: true
